# Generated by Django 6.0.1 on 2026-01-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='status',
        ),
    ]
