# Generated by Django 6.0.1 on 2026-01-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_remove_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=100, help_text='Max number of students allowed'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_number',
            field=models.CharField(default='000000000', help_text='Contact number for queries', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(default='Student Council', max_length=100),
        ),
    ]
